language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION_CEILING=1.7 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION_CEILING=1.7 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION_CEILING=1.7 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
  - DJANGO_VERSION_CEILING=1.8 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION_CEILING=1.8 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION_CEILING=1.8 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
install:
  - pip install -v "Django<$DJANGO_VERSION_CEILING" MySQL-python psycopg2
  - "pip install -q flake8 pylint pylint-django"
  - "pip install -e ."
before_script:
  - "mysql -e 'create database testdb;'"
  - "psql -c 'create database testdb;' -U postgres"
script:
  - "python setup.py test"
  - "./lint.sh"
